# Generated by Django 5.0.1 on 2024-01-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media', verbose_name='Design Image')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('text', models.TextField(max_length=255, verbose_name='About Design')),
            ],
            options={
                'verbose_name': 'Design',
                'verbose_name_plural': 'Design',
            },
        ),
    ]
