# Generated by Django 5.0.1 on 2024-01-16 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_logo_alter_design_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logo',
            old_name='logo',
            new_name='img',
        ),
    ]
