# Generated by Django 5.0.1 on 2024-01-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_logo_logo_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='meia', verbose_name='Image')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('text1', models.TextField(verbose_name='First Text')),
                ('text2', models.TextField(verbose_name='Second Text')),
                ('text3', models.TextField(verbose_name='Third Text')),
            ],
            options={
                'verbose_name': 'About Team',
                'verbose_name_plural': 'About Team',
            },
        ),
    ]
