# Generated by Django 5.0.1 on 2024-01-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_aboutteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Gallery One',
                'verbose_name_plural': 'Gallery One',
            },
        ),
    ]
