# Generated by Django 5.0.1 on 2024-01-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_galleryone_image_galleryone_image1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(null=True, upload_to='media', verbose_name='First Image')),
                ('image2', models.ImageField(null=True, upload_to='media', verbose_name='Second Image')),
                ('image3', models.ImageField(null=True, upload_to='media', verbose_name='Third Image')),
            ],
            options={
                'verbose_name': 'Second Gallery',
                'verbose_name_plural': 'Second Gallery',
            },
        ),
    ]
