# Generated by Django 5.0.1 on 2024-01-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_secondgallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(null=True, upload_to='media', verbose_name='First Image')),
                ('image2', models.ImageField(null=True, upload_to='media', verbose_name='Second Image')),
                ('image3', models.ImageField(null=True, upload_to='media', verbose_name='Third Image')),
                ('image4', models.ImageField(null=True, upload_to='media', verbose_name='Fourth Image')),
            ],
            options={
                'verbose_name': 'Third Gallery',
                'verbose_name_plural': 'Third Gallery',
            },
        ),
    ]
